In [ ]:
import numpy as np
#RANDOM MODULE IS SUB-PACKAGE OF NUMPY

In [ ]:
A=np.random.rand(1)
print(A)


[0.20479376]


In [ ]:
A=np.random.rand(8,4)#and-range is between 0 and 1
print(A)

[[0.14197642 0.14832639 0.08394002 0.16473041]
 [0.08781138 0.72996183 0.19222715 0.19669757]
 [0.86730335 0.84878392 0.95370913 0.47743522]
 [0.95875577 0.77300059 0.78345844 0.69786296]
 [0.21718777 0.95942099 0.94379257 0.90747443]
 [0.8230649  0.01671347 0.31122516 0.51482071]
 [0.46105468 0.92360271 0.42897542 0.37265315]
 [0.6335501  0.88040097 0.43073379 0.98474677]]


In [ ]:
A=10*np.random.rand(8,4)
print(A)

[[7.34372474 1.14866124 7.780316   5.27935365]
 [1.13026749 1.26729351 0.33888636 7.87087727]
 [4.43640979 4.54494655 9.27956262 4.91331341]
 [1.29181453 9.73202125 2.36382829 1.95456925]
 [7.13478346 3.57517994 5.72408271 6.17393826]
 [9.5938405  6.96882109 8.70186277 6.63782461]
 [0.04085947 1.99700795 3.56595916 5.10551096]
 [1.85629953 3.69166525 0.56883826 5.17916411]]


In [ ]:
A= np.floor(10*np.random.rand(8,4))
print(A)

[[1. 5. 0. 5.]
 [8. 3. 0. 5.]
 [6. 1. 5. 1.]
 [1. 5. 7. 2.]
 [0. 6. 2. 8.]
 [9. 1. 5. 0.]
 [3. 3. 4. 8.]
 [9. 6. 1. 3.]]


In [ ]:
A=np.arange(1,33).reshape(8,4)
print(A)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [ ]:
np.vsplit(A,4)#the spliting number should divide no of rows(8/4)

NameError: name 'np' is not defined

In [ ]:
np.vsplit(A,(3,5))#split it after 3rd row and 5th row

[array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16],
        [17, 18, 19, 20]]),
 array([[21, 22, 23, 24],
        [25, 26, 27, 28],
        [29, 30, 31, 32]])]

In [ ]:
B=np.arange(1,33).reshape(4,8)
print(B)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]]


In [ ]:
np.hsplit(B,4)


[array([[ 1,  2],
        [ 9, 10],
        [17, 18],
        [25, 26]]),
 array([[ 3,  4],
        [11, 12],
        [19, 20],
        [27, 28]]),
 array([[ 5,  6],
        [13, 14],
        [21, 22],
        [29, 30]]),
 array([[ 7,  8],
        [15, 16],
        [23, 24],
        [31, 32]])]

In [ ]:
np.hsplit(B,(4,8))

[array([[ 1,  2,  3,  4],
        [ 9, 10, 11, 12],
        [17, 18, 19, 20],
        [25, 26, 27, 28]]),
 array([[ 5,  6,  7,  8],
        [13, 14, 15, 16],
        [21, 22, 23, 24],
        [29, 30, 31, 32]]),
 array([], shape=(4, 0), dtype=int64)]

In [ ]:
np.hsplit(B,(3,7))

[array([[ 1,  2,  3],
        [ 9, 10, 11],
        [17, 18, 19],
        [25, 26, 27]]),
 array([[ 4,  5,  6,  7],
        [12, 13, 14, 15],
        [20, 21, 22, 23],
        [28, 29, 30, 31]]),
 array([[ 8],
        [16],
        [24],
        [32]])]

  Trigonometry

In [ ]:
np.pi

3.141592653589793

In [ ]:
A=[np.pi/4,np.pi/3,np.pi/2,np.pi]
print(A)

[0.7853981633974483, 1.0471975511965976, 1.5707963267948966, 3.141592653589793]


In [ ]:
B=np.rad2deg(A) #convert radians to degrees
print(B)

[ 45.  60.  90. 180.]


In [ ]:
np.deg2rad(B) #convert degrees to radians

array([0.78539816, 1.04719755, 1.57079633, 3.14159265])

In [ ]:
np.sin(A) #radians

array([7.07106781e-01, 8.66025404e-01, 1.00000000e+00, 1.22464680e-16])

In [ ]:
np.cos(1)

NameError: name 'np' is not defined

In [ ]:
np.tan(1)

1.5574077246549023

Statistics

In [ ]:
st=np.array([23,45,67,89,21,34])

In [ ]:
np.mean(st)


46.5

In [ ]:
np.median(st)

39.5

In [ ]:
np.std(st)

24.452334585202017

In [ ]:
np.var(st)

597.9166666666666

In [ ]:
C=np.arange(1,5).reshape(2,2)
print(C)

[[1 2]
 [3 4]]


In [ ]:
np.linalg.inv(C)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [ ]:
C=np.arange(1,25).reshape(6,4)
print(np.argmax(C))

23


In [ ]:
c=10*np.random.rand(24).reshape(6,4)
print(c)

[[7.26126384 1.840976   8.09475325 3.91341004]
 [2.09073794 5.14149737 5.98693212 6.33567496]
 [8.22651198 5.85249331 0.12234671 0.66583234]
 [2.51993646 5.43962926 9.79090123 8.25239397]
 [4.72086367 5.65630348 9.87511975 7.7751098 ]
 [4.76785407 8.01069594 8.56926444 6.25142128]]


In [ ]:
print(np.argmax(c))

18


In [ ]:
print(np.argmax(C,axis=1))

[3 3 3 3 3 3]


In [ ]:
print(np.argmax(C,axis=0))


[5 5 5 5]


In [ ]:
print(np.argmin(C,axis=0))


[0 0 0 0]


In [ ]:
print(np.argmin(C,axis=1))


[0 0 0 0 0 0]


searching

In [ ]:
a = np.array([34,56,7,17,88,91])
print(np.where(a%2==0)) #where condition is nothing but if



(array([0, 1, 4]),)


In [ ]:
print(np.where(a%2!=0))

(array([2, 3, 5]),)


In [ ]:
b=np.array([24,16,7,17,54,60])
print(np.where(b%6==0))

(array([0, 4, 5]),)


In [ ]:
#for sorted array only
d=np.array([11,12,13,14,15])
x=np.searchsorted(d,14)
print(x)

3


In [ ]:
#sorting array
a=np.array(["apple","mango","cherry"])
print(np.sort(a))
b=np.array(["true","false","true"])
print(np.sort(b))

['apple' 'cherry' 'mango']
['false' 'true' 'true']


In [ ]:
#2d sort - sorting happens within row
arr=np.array([[3,2,4],[5,0,1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [ ]:
#filter
arr=np.array([40,43,50,44,67,78])
filt = np.where(arr%2 == 0)
print(filt)

(array([0, 2, 3, 5]),)


In [ ]:
arr[filt]

array([40, 50, 44, 78])

In [ ]:
names = np.array(["divya","vyshu","jaya","reethi","shiva"])
initials = np.array(["k","N","S","V","P"])
for i,j in zip(initials,names):
  print(i,".",j)

k . divya
N . vyshu
S . jaya
V . reethi
P . shiva


In [ ]:
#multiplication of two arrays
a1 = np.array([10,20,30,40,50,60])
a2 = np.array([20,21,22,23,24,25])
n = np.multiply(a1,a2)
print(n)

[ 200  420  660  920 1200 1500]


In [ ]:
#division od two arrays
a1 = np.array([10,20,30,40,50,60])
a2 = np.array([20,21,22,23,24,25])
n = np.multiply(a1,a2)
print(n)

[ 200  420  660  920 1200 1500]


In [ ]:
#modulo operation between two arrays
a1 = np.array([10,20,30,40,50,60])
a2 = np.array([20,21,22,23,24,25])
n = np.mod(a1,a2)
print(n)

[10 20  8 17  2 10]


In [ ]:
#dividemodulo between two arrays
a1 = np.array([10,20,30,40,50,60])
a2 = np.array([20,21,22,23,24,25])
n = np.divmod(a1,a2)
print(n)

(array([0, 0, 1, 1, 2, 2]), array([10, 20,  8, 17,  2, 10]))


In [ ]:
#logarithms
a=1.2
print(np.log(a)) #natural log e

0.1823215567939546


In [ ]:
a=1.2
print(np.log2(a)) #log base 2

0.2630344058337938


In [ ]:
a=1.2
print(np.log10(a)) #log base 10

0.07918124604762482


In [ ]:
a=np.array([1,1.2,3,4])
print(np.log(a)) #natural log

[0.         0.18232156 1.09861229 1.38629436]


In [ ]:
#cummulative product
a=np.array([1,2,3,4,5])
x=np.cumprod(a)
print(x)

[  1   2   6  24 120]


In [ ]:
#cummalative sum
a=np.array([1,2,3,4,5])
x=np.cumsum(a)
print(x)

[ 1  3  6 10 15]


In [ ]:
# difference
a=np.array([1,2,3,4,5])
x=np.diff(a)
print(x)


[1 1 1 1]


In [ ]:
#LCM
n1=455
n2=665
x=np.lcm(n1,n2)
print(x)

8645


In [ ]:
#gcd
n1=455
n2=556
x=np.gcd(n1,n2)
print(x)

1


In [ ]:
a=np.array([5,25,50])
g=np.gcd.reduce(a) #take multiple inputs and give single output
print(g)

5


In [ ]:
a=np.array([4,8,12,40])
g=np.lcm.reduce(a)
print(g)

120
